# data.py
# VERİ KAYNAĞI: MEB 2024 LGS Yerleştirme Sonuçları & Kullanıcı CSV Dosyası
# DÜZELTME: Okul imkanları (Spor, Yemek, Konferans vb.) CSV dosyasındaki "Yok" ibarelerine göre birebir işlenmiştir.

OKUL_VERITABANI = [
    # --- %0 - %1 ARASI ---
    {'ad': 'Ankara Fen Lisesi', 'ilce': 'Çankaya', 'puan': 494.5096, 'yuzdelik': 0.08, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Prof. Dr. Aziz Sancar Fen Lisesi', 'ilce': 'Çankaya', 'puan': 493.8037, 'yuzdelik': 0.21, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ankara Pursaklar Fen Lisesi', 'ilce': 'Pursaklar', 'puan': 489.0189, 'yuzdelik': 0.31, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ankara Erman Ilıcak Fen Lisesi', 'ilce': 'Sincan', 'puan': 481.8925, 'yuzdelik': 0.77, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Atatürk Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 481.7319, 'yuzdelik': 0.79, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Özdemir Bayraktar Havacılık ve Uzay Teknolojileri MTAL', 'ilce': 'Sincan', 'puan': 480.2425, 'yuzdelik': 0.96, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    
    # --- %1 - %3 ARASI ---
    {'ad': 'Cumhuriyet Fen Lisesi', 'ilce': 'Çankaya', 'puan': 477.3322, 'yuzdelik': 1.09, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Keçiören Vatansever Şehit Tümgeneral Aydoğan Aydın Fen Lisesi', 'ilce': 'Keçiören', 'puan': 476.4021, 'yuzdelik': 1.31, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Yenimahalle Fen Lisesi', 'ilce': 'Yenimahalle', 'puan': 474.6942, 'yuzdelik': 1.52, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': True, 'kantin': True},
    {'ad': 'Özkent Akbilek Fen Lisesi', 'ilce': 'Etimesgut', 'puan': 470.7507, 'yuzdelik': 1.90, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'ASELSAN Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 470.5631, 'yuzdelik': 1.95, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ankara Atatürk Lisesi', 'ilce': 'Çankaya', 'puan': 467.2796, 'yuzdelik': 2.31, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'ASELSAN Mesleki ve Teknik Anadolu Lisesi (Hazırlık)', 'ilce': 'Yenimahalle', 'puan': 466.8646, 'yuzdelik': 2.38, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Gazi Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 465.7329, 'yuzdelik': 2.57, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    
    # --- %3 - %5 ARASI ---
    {'ad': 'Mehmet Emin Resulzade Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 462.6738, 'yuzdelik': 3.12, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Dr.Binnaz Ege-Dr.Rıdvan Ege Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 458.7408, 'yuzdelik': 3.86, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Şehit Oğuzhan Yaşar Anadolu Lisesi', 'ilce': 'Etimesgut', 'puan': 456.9634, 'yuzdelik': 4.22, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Hacı Ömer Tarman Anadolu Lisesi (İngilizce)', 'ilce': 'Çankaya', 'puan': 455.5786, 'yuzdelik': 4.50, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Nermin Mehmet Çekiç Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 453.6937, 'yuzdelik': 4.90, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    
    # --- %5 - %10 ARASI ---
    {'ad': 'Hacı Ömer Tarman Anadolu Lisesi (Almanca)', 'ilce': 'Çankaya', 'puan': 452.2608, 'yuzdelik': 5.21, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Vecihi Hürkuş Anadolu Lisesi', 'ilce': 'Mamak', 'puan': 450.932, 'yuzdelik': 5.51, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Tevfik İleri Anadolu İmam Hatip Lisesi (Hazırlık)', 'ilce': 'Yenimahalle', 'puan': 449.8055, 'yuzdelik': 5.77, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Mamak Fen Lisesi', 'ilce': 'Mamak', 'puan': 445.0946, 'yuzdelik': 5.81, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': True, 'kantin': True}, 
    {'ad': 'Ayrancı Anadolu Lisesi (İngilizce)', 'ilce': 'Çankaya', 'puan': 448.7779, 'yuzdelik': 6.01, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Cezeri Yeşil Teknoloji MTAL (Yenilenebilir Enerji)', 'ilce': 'Etimesgut', 'puan': 447.8821, 'yuzdelik': 6.22, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Tevfik İleri Anadolu İmam Hatip Lisesi', 'ilce': 'Yenimahalle', 'puan': 446.4719, 'yuzdelik': 6.57, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Betül Can Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 444.6465, 'yuzdelik': 7.03, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Mustafa Azmi Doğan Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 443.1534, 'yuzdelik': 7.42, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Altındağ Yıldırım Beyazıt Fen Lisesi', 'ilce': 'Altındağ', 'puan': 441.7915, 'yuzdelik': 7.77, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Süleyman Demirel Anadolu Lisesi', 'ilce': 'Etimesgut', 'puan': 440.0664, 'yuzdelik': 8.24, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ayhan Sümer Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 438.3585, 'yuzdelik': 8.71, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ümitköy Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 438.1636, 'yuzdelik': 8.76, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ayrancı Anadolu Lisesi (Çince)', 'ilce': 'Çankaya', 'puan': 437.8943, 'yuzdelik': 8.84, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Aydınlıkevler Anadolu Lisesi', 'ilce': 'Altındağ', 'puan': 436.421, 'yuzdelik': 9.25, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Mustafa Hakan Güvençer Fen Lisesi', 'ilce': 'Kahramankazan', 'puan': 435.6174, 'yuzdelik': 9.48, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Cezeri Yeşil Teknoloji MTAL (Elektrik-Elektronik)', 'ilce': 'Etimesgut', 'puan': 435.5367, 'yuzdelik': 9.51, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ankara Lisesi', 'ilce': 'Altındağ', 'puan': 433.8407, 'yuzdelik': 10.0, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': False, 'kantin': True},
    
    # --- %10 ve ÜZERİ ---
    {'ad': 'Şehit Ömer Halisdemir Anadolu Lisesi', 'ilce': 'Etimesgut', 'puan': 433.0315, 'yuzdelik': 10.24, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Fatih Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 432.2273, 'yuzdelik': 10.48, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Şehit Ömer Halisdemir Anadolu İmam Hatip Lisesi', 'ilce': 'Yenimahalle', 'puan': 430.7063, 'yuzdelik': 10.94, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Yavuz Sultan Selim Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 428.1724, 'yuzdelik': 11.71, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Polatlı TOBB Fen Lisesi', 'ilce': 'Polatlı', 'puan': 424.3292, 'yuzdelik': 12.92, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Meliha Hasanali Bostan Çubuk Fen Lisesi', 'ilce': 'Çubuk', 'puan': 423.8322, 'yuzdelik': 13.08, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Pursaklar Ayyıldız Anadolu Lisesi', 'ilce': 'Pursaklar', 'puan': 423.2374, 'yuzdelik': 13.27, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Gazi Lisesi', 'ilce': 'Altındağ', 'puan': 422.3387, 'yuzdelik': 13.57, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'TUSAŞ Şehit Hakan Gülşen MTAL', 'ilce': 'Kahramankazan', 'puan': 421.3274, 'yuzdelik': 13.9, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Şehit Cengiz Polat Anadolu İmam Hatip Lisesi', 'ilce': 'Etimesgut', 'puan': 418.9172, 'yuzdelik': 14.71, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Gölbaşı Anadolu Lisesi', 'ilce': 'Gölbaşı', 'puan': 418.1924, 'yuzdelik': 14.95, 'spor': True, 'yemek': False, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Aktepe Şehit Köksal Kaşaltı Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 417.8427, 'yuzdelik': 15.08, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ankara Türk Telekom Sosyal Bilimler Lisesi', 'ilce': 'Çankaya', 'puan': 409.0835, 'yuzdelik': 16.50, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Hasan Ali Yücel Sosyal Bilimler Lisesi', 'ilce': 'Çankaya', 'puan': 406.8408, 'yuzdelik': 17.20, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ömer Halisdemir Anadolu İmam Hatip Lisesi (Fen ve Sosyal Bilimler)', 'ilce': 'Yenimahalle', 'puan': 399.0763, 'yuzdelik': 18.50, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Sabahattin Zaim Sosyal Bilimler Lisesi', 'ilce': 'Altındağ', 'puan': 395.5901, 'yuzdelik': 19.10, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ali-Hasan Coşkun Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 392.4277, 'yuzdelik': 19.80, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ankara Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Altındağ', 'puan': 382.7212, 'yuzdelik': 20.40, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Ulus Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Altındağ', 'puan': 378.8953, 'yuzdelik': 20.62, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Kocatepe Mimar Kemal Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 376.5342, 'yuzdelik': 21.43, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Batıkent Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 375.3214, 'yuzdelik': 21.84, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Yenimahalle Zeynep-Salih Alp Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 374.9082, 'yuzdelik': 21.98, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Şehit Sercan Öztürk Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 371.7458, 'yuzdelik': 23.09, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Mamak Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Mamak', 'puan': 365.421, 'yuzdelik': 25.36, 'spor': True, 'yemek': True, 'konferans': False, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Keçiören Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 363.8041, 'yuzdelik': 25.96, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Abidinpaşa Anadolu Lisesi', 'ilce': 'Mamak', 'puan': 361.2683, 'yuzdelik': 26.93, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Kanuni Sultan Süleyman Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 330.12, 'yuzdelik': 28.5, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Etimesgut Şehit Salih Helvacı Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Etimesgut', 'puan': 320.4, 'yuzdelik': 31.2, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Yenimahalle Ostim Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 288.73, 'yuzdelik': 40.81, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': True, 'kantin': True},
    {'ad': 'İncirli Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 286.4327, 'yuzdelik': 42.00, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'İskitler Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Altındağ', 'puan': 286.4327, 'yuzdelik': 42.00, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Çankaya Borsa İstanbul Turizm Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 285.3, 'yuzdelik': 43.50, 'spor': False, 'yemek': False, 'konferans': True, 'bilg_lab': False, 'fen_lab': False, 'kantin': False},
    {'ad': 'Keçiören İMKB Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Keçiören', 'puan': 279.995, 'yuzdelik': 45.10, 'spor': False, 'yemek': True, 'konferans': False, 'bilg_lab': False, 'fen_lab': True, 'kantin': False},
    {'ad': 'Balgat Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 258.098, 'yuzdelik': 60.32, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': True, 'kantin': True},
    {'ad': 'Nallıhan Şehit Hulki Beydili Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Nallıhan', 'puan': 258.8, 'yuzdelik': 60.00, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Sincan Ahmet Andiçen Ticaret Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Sincan', 'puan': 238.76, 'yuzdelik': 65.0, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': False, 'kantin': False},
    {'ad': 'Altındağ Atatürk Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Altındağ', 'puan': 235.0, 'yuzdelik': 70.0, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': True, 'kantin': False},
    {'ad': 'Altındağ Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Altındağ', 'puan': 222.4137, 'yuzdelik': 75.0, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': False, 'fen_lab': True, 'kantin': True},
    {'ad': 'Haymana Anadolu İmam Hatip Lisesi', 'ilce': 'Haymana', 'puan': 150.5, 'yuzdelik': 96.2, 'spor': False, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Çankaya İMKB Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Çankaya', 'puan': 430.7063, 'yuzdelik': 10.94, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Şentepe Şehit Volkan Canöz Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 418.9172, 'yuzdelik': 14.71, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
    {'ad': 'Yenimahalle Şehit Mehmet Şengül Mesleki ve Teknik Anadolu Lisesi', 'ilce': 'Yenimahalle', 'puan': 417.8427, 'yuzdelik': 15.08, 'spor': True, 'yemek': True, 'konferans': True, 'bilg_lab': True, 'fen_lab': True, 'kantin': True},
]